[package]
name = "mood-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
dialoguer = "0.11.0"
daemonize = "0.5.0"
